.TH "gkeys" "1" "0.1" "GKEYS" ""
.SH NAME
gkeys \- Gentoo OpenPGP key management tool
.SH SYNOPSIS
.B gkeys
[\fB\-h\fR] [\fB\-c\fR \fICONFIG\fR] [\fB\-D\fR \fI{WARNING,INFO,FATAL,NOTSET,WARN,DEBUG,ERROR,CRITICAL}\fR] [\fBSUBCOMMAND] [\fBSUBCOMMAND-OPTION] ...
.SH DESCRIPTION
.PP
Gentoo Keys is a Python based project that aims to manage 
the GPG keys used for validation on users and Gentoo's infrastracutre servers. 
Gentoo Keys is able to verify GPG keys used for Gentoo's release media, 
such as installation CD's, Live DVD's, packages and other GPG signed documents.

.SH OPTIONAL ARGUMENTS
.IP "-h, --help"
show this help message and exit
.IP "-c \fICONFIG\fR, --config \fICONFIG"
The path to an alternate config file
.IP "-D, --debug \fI{WARNING,INFO,FATAL,NOTSET,WARN,DEBUG,ERROR,CRITICAL}\fR"
The logging level to set for the logfile

.SH SUBCOMMANDS
.SH GENERAL
.IP sign
Sign a file
.IP verify
File verification action
.SH KEYS
.IP check-key
Check keys actions
.IP import-key
Add a specified key to a specified keyring
.IP installed
Lists the installed key directories
.IP install-key
Install a key from the seed(s)
.IP search-key
Search for a key's seed field in the installed keys db
.IP list-key
Pretty-print the selected seed file or nick
.IP move-key
Rename an installed key
.IP refresh-key
Calls gpg with the --refresh-keys option
.IP remove-key
Remove an installed key
.IP spec-check
Check keys actions
.SH SEEDS
.IP add-seed
Add or replace a key in the selected seed file(s)
.IP fetch-seed
Download the selected seed file(s)
.IP list-cats
List seed file definitions found in the config
.IP list-seed
Pretty-print the selected seed file(s)
.IP list-seedfiles
List seed files found in the configured seed directory
.IP move-seed
Move keys between seed files
.IP remove-seed
Remove a key from the selected seed file(s)

.SH REPORTING BUGS
Submit bug reports to http://bugs.gentoo.org.
.br
Please assign bug to <gkeys@gentoo.org> email alias. 

.SH COPYRIGHTS
Gentoo Keys is under GPL-2 License.

.SH AUTHORS
.br
Brian Dolbec <dolsen@gentoo.org>
.br
Pavlos Ratis <dastergon@gentoo.org>

.SH "SEE ALSO"
.BR gkeys-sign (1),
.BR gkeys-verify(1),
.BR gkeys-check-key(1),
.BR gkeys-import-key(1),
.BR gkeys-installed(1),
.BR gkeys-install-key(1),
.BR gkeys-search-key(1),
.BR gkeys-list-key(1),
.BR gkeys-move-key(1),
.BR gkeys-remove-key(1),
.BR gkeys-spec-check(1),
.BR gkeys-add-seed(1),
.BR gkeys-fetch-seed(1),
.BR gkeys-list-cats(1),
.BR gkeys-list-seed(1),
.BR gkeys-list-seedfiles(1),
.BR gkeys-move-seed(1),
.BR gkeys-remove-seed(1)
